services:
  paradisias-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paradisias-hotel-app
    ports:
      - "9000:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - TZ=Africa/Abidjan
    volumes:
      # Volume pour les logs nginx
      - ./logs:/var/log/nginx
    labels:
      - "com.docker.compose.project=paradisias"
      - "com.docker.compose.service=app"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service nginx-proxy optionnel pour le reverse proxy
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: paradisias-proxy
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - paradisias-app
  #   restart: unless-stopped

networks:
  default:
    name: paradisias-network 