services:
  paradisias-app:
    # Utiliser l'image depuis Docker Hub au lieu de build local
    image: votre-username/paradisias-hotel:latest
    container_name: paradisias-hotel-app
    ports:
      - "9000:80"
      # - "443:443"
    restart: unless-stopped
    environment:
      - TZ=Africa/Abidjan
      - API_BASE_URL=http://localhost:9001

    volumes:
      # Volume pour les logs nginx
      - ./logs:/var/log/nginx
    labels:
      - "com.docker.compose.project=paradisias"
      - "com.docker.compose.service=app"
      
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: paradisias-network