export { default as DataTable } from './DataTable.vue'
export { default as Pagination } from './Pagination.vue'
export { default as Modal } from './Modal.vue'
export { default as PrimaryButton } from './PrimaryButton.vue'
export { default as OptimizedImage } from './OptimizedImage.vue' 